---
title: "flex_dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r, include=TRUE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(viridis)
library(plotly)
```


```{r}
data("instacart")
instacart_clean = instacart %>% 
  janitor::clean_names() %>% 
  mutate(order_dow = recode(order_dow, `0` = "Sunday", `1` = "Monday", `2` = "Tuesday", `3` = "Wednesday", `4` = "Thursday", `5` = "Friday", `6` = "Saturday"))

```


```{r}
set.seed(5)
instacart_clean_sample = instacart %>% 
  sample_n(100)
```

```{r}
instacart_clean_sample %>%
  group_by(order_dow) %>%
  summarize(orders = n()) %>%
  plot_ly(x = ~order_dow, y = ~orders, type = "bar") %>% 
   layout(
     title = "DOW & Orders")
```

```{r}
instacart_clean_sample %>%
  plot_ly(x = ~order_dow, y = ~order_hour_of_day, type = "box") %>% 
   layout(
     title = "Distribution", 
     yaxis = list(title = "Hour"), 
     xaxis = list(title = "Day of Week")
     )
```

```{r }

instacart_clean_sample %>% 
  group_by(aisle, department) %>% 
  summarize(ordered_amount = n()) %>% 
  plot_ly(x = ~aisle, y = ~ordered_amount, type = "scatter", mode = "markers",
          alpha = 0.5) %>% 
  layout(
     title = "Number of Orders Per Aisle", 
     yaxis = list(title = "Hour"), 
      xaxis = list(title = "Day of Week")
  )
```
